In [1]:
import torch 

t1, t2 = torch.randn(2,3,3)

sum = t1 + t2

mult = t1 * t2
print(mult)

print(mult[0,0])

t2 = torch.tensor([[2.0],[1.0]])
print(t2.shape)

tensor([[ 0.0262,  0.0833, -0.0098],
        [ 1.0173, -0.0128, -2.1485],
        [-0.0077,  3.1505, -0.0656]])
tensor(0.0262)
torch.Size([2, 1])


In [2]:
cambio = mult.view(1,9)
print(cambio)

cambio2 = mult.view(-1)
print(cambio2)

tensor([[ 0.0262,  0.0833, -0.0098,  1.0173, -0.0128, -2.1485, -0.0077,  3.1505,
         -0.0656]])
tensor([ 0.0262,  0.0833, -0.0098,  1.0173, -0.0128, -2.1485, -0.0077,  3.1505,
        -0.0656])


In [3]:
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x + 2
y.backward()
print(x.grad)


tensor([7.])


In [4]:
#Construccion de un modelo
import torch.nn as nn

class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.LL1 = nn.Linear(2,1)
        self.act1 = nn.Sigmoid()
    
    def forward(self, x):
        return self.act1(self.LL1(x))
    
tensor = torch.tensor([1.0, 2.0])
model = SimpleNet()

output = model(tensor)
print(output)

tensor([0.5342], grad_fn=<SigmoidBackward0>)


In [5]:
'''1️ Crea un tensor 3x3 con valores aleatorios entre 0 y 1.
2️ Multiplica todos los elementos por 10 y conviértelos a enteros.
3️ Selecciona la fila con el valor máximo en la segunda columna.
4️ Aplica mean y std (media y desviación) al tensor.
5️ Convierte el tensor a un array de NumPy y viceversa'''

import torch
import numpy as np

matriz1 = np.round(np.random.rand(3,3),3)
tensor1 = torch.tensor(matriz1)

tensor1 = tensor1 * 10
tensor2 = tensor1.int()
print(tensor2)

print(tensor1.mean())
print(tensor1.std())

array = np.array(tensor1)
print(array)
tensor = torch.tensor(array)
print(tensor)



tensor([[9, 7, 3],
        [5, 4, 6],
        [7, 8, 2]], dtype=torch.int32)
tensor(6.0711, dtype=torch.float64)
tensor(2.5167, dtype=torch.float64)
[[9.98 7.08 3.18]
 [5.82 4.58 6.25]
 [7.12 8.59 2.04]]
tensor([[9.9800, 7.0800, 3.1800],
        [5.8200, 4.5800, 6.2500],
        [7.1200, 8.5900, 2.0400]], dtype=torch.float64)


C:\Users\karl1\AppData\Local\Temp\ipykernel_21088\3967746375.py:20: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  array = np.array(tensor1)
