In [51]:
import torch 

t1, t2 = torch.randn(2,3,3)

sum = t1 + t2

mult = t1 * t2
print(mult)

print(mult[0,0])

t2 = torch.tensor([[2.0],[1.0]])
print(t2.shape)

tensor([[-3.7530e+00, -1.2007e-01, -3.6612e-01],
        [ 5.8468e-02, -1.2991e+00, -2.5813e-02],
        [ 6.1459e-01, -3.7226e-03,  2.3706e-01]])
tensor(-3.7530)
torch.Size([2, 1])


In [33]:
cambio = mult.view(1,9)
print(cambio)

cambio2 = mult.view(-1)
print(cambio2)

tensor([[ 2.1639e-02,  2.8293e-01, -6.0509e-01, -2.7317e-01,  1.0975e-01,
         -4.8090e-01,  7.0535e-01, -2.6078e-04, -7.3655e-01]])
tensor([ 2.1639e-02,  2.8293e-01, -6.0509e-01, -2.7317e-01,  1.0975e-01,
        -4.8090e-01,  7.0535e-01, -2.6078e-04, -7.3655e-01])


In [45]:
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x + 2
y.backward()
print(x.grad)


tensor([7.])


In [50]:
#Construccion de un modelo
import torch.nn as nn

class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.LL1 = nn.Linear(2,1)
        self.act1 = nn.Sigmoid()
    
    def forward(self, x):
        return self.act1(self.LL1(x))
    
tensor = torch.tensor([1.0, 2.0])
model = SimpleNet()

output = model(tensor)
print(output)

tensor([0.5223], grad_fn=<SigmoidBackward0>)
